### ISSUE TITLE
Issues with manual build

### ISSUE THREAD

**Issue by beatcracker** [Jaykul/NancyPS#2]
Here is the issues I've encountered while trying to build `NancyPS` locally:

* #### `Package Source 'NuGet' exists` during build

If I run unmodified `Build.ps1` script I get this error:

```none
Register-PackageSource : Package Source 'NuGet' exists.
At X:\NancyPS\Build.ps1:141 char:21
+ ...     $Name = Register-PackageSource NuGet -Location 'https://www.nuget ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (Microsoft.Power...erPackageSource:RegisterPackageSource) [Register-PackageSource], Exception
    + FullyQualifiedErrorId : PackageSourceExists,Microsoft.PowerShell.PackageManagement.Cmdlets.RegisterPackageSource
```

Not sure why, but I have NuGet source url registered with trailing slash: `https://www.nuget.org/api/v2/`
This throws the build script off, since it expects it to be without trailing slash: [Build.ps1#L139](https://github.com/Jaykul/NancyPS/blob/master/Build.ps1#L139)

* #### `Unable to find type [Nancy.NancyModule]` on module import

After successful build, when I try to import the module this error occurs:

```none
Unable to find type [Nancy.NancyModule].
At X:\NancyPS\1.0.1\NancyPS.psm1:5 char:81
+ ...  -ReferencedAssemblies Microsoft.CSharp, ([Nancy.NancyModule].Assembl ...
+                                               ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Nancy.NancyModule:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

This happens because `NancyPS.psd1` module manifest doesn't have `RequiredAssemblies` property defined: [NancyPS.psd1#L49](https://github.com/Jaykul/NancyPS/blob/master/src/NancyPS.psd1#L49)

To fix this error, I've uncommented `RequiredAssemblies` definition in the module manifest and added this code to the `build` function in the build script:

```posh
## Update RequiredAssemblies:
if ($RequiredAssemblies = Get-ChildItem -Path $LibPath -Filter '*.dll' | % {Join-Path $_.Directory.Name $_.Name}) {
    Trace-Message "       Update RequiredAssemblies"
    Update-Manifest $ReleaseManifest -PropertyName RequiredAssemblies -Value $RequiredAssemblies
}
```

* #### `The term 'Set-NancyHandler' is not recognized`  on module import

After successful build, when I try to import the module this error occurs:

```none
Set-NancyHandler : The term 'Set-NancyHandler' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At X:\NancyPS\1.0.1\NancyPS.psm1:8 char:1
+ Set-NancyHandler -Path "/" -Handler { "Welcome to Nancy" }function Ge ...
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-NancyHandler:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

This happens because during the build process all functions are bundled into the `NancyPS.psm1` and [_classes.ps1#L8](https://github.com/Jaykul/NancyPS/blob/master/src/private/_classes.ps1#L8) is processed first (filename starts with underscore). This means that it can't use `Set-NancyHandler` function since it's placed further down in the  `NancyPS.psm1`.

For now, I've just commented out this line and added linebreak after it.

---

P.S. I've found https://github.com/gpduck/NancyPS fork, which also fixes a couple of other issues:

* [Fixed class reference](https://github.com/Jaykul/NancyPS/commit/ea36d606c9b0eb94e5cf7161d6e38729caf02263)
* [Fixes AutomaticUrlReservations parameter.](https://github.com/Jaykul/NancyPS/commit/cc3ec3f501fc2f18c259a3e8d2c604a54d6ec30c)

This allowed me to successfully start NancyPS and test simple handler.

**Comment by Jaykul** [comment]
I'll update the build script with my latest which uses `-match` instead of `-eq` to fix the nuget problem. I'm always refining this as I use it in new projects.

The RequiredAssemblies should just be:

```posh
RequiredAssemblies = @(".\lib\Nancy.dll", ".\lib\Nancy.Hosting.Self.dll")
```
And Set-NancyHandler should be fine ... unless maybe that's a problem with an older version of PowerShell?
